language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_install:
    - composer self-update

install:
    - composer install

script: ./vendor/bin/phpunit

after_script:
    - php vendor/bin/coveralls -v
